### ISSUE TITLE
Export button needs more affordance to tell the user it's not going to function

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#10]
I thought the below was the problem, but it was actually that I just didn't select a version number - maybe we could tell the user what's missing to get the Export button to light up? 

Try to migrate a folder of files that has previously been migrated to a new folder.
>> Nothing happens.
Ideally this should work  or at least the user should get a message saying that the files have already been migrated (how exactly does it know?)

**Comment by lillismith** [comment]
https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/09c7cf97-8769-4066-9af3-3ef713901fb2

**Comment by johnpierson** [comment]
I would say to test the latest release to see if this is still the case (because of the file trust stuff)

https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/15744724/6ac21c72-24d9-4fd2-b72d-5de5f4729853

**Comment by johnpierson** [comment]
This should be resolved now in the latest releases.

**Comment by johnpierson** [comment]
Add *Required or turn the trusted checkbox red to help alert users
