### ISSUE TITLE
Workspace references forces itself open over the  Graph Migration Assistant 

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#11]
See attached video. When you run the Graph Migration Assistant, the workspace references extension forces itself open every time you open a graph with problematic dependencies.  Ideally the Graph Migration Assistant would stay on top the whole time it's running. 

https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/23299503-288a-4c6a-bcdc-42c1a6339ea3

**Comment by QilongTang** [comment]
Related task tracked as https://jira.autodesk.com/browse/DYN-5916
