### ISSUE TITLE
Folder path boxes appearance

### ISSUE THREAD

**Issue by twastvedt** [DynamoDS/DynamoGraphUpdater#17]
Nitpick, and low priority I think. Could the folder path boxes match those in the rest of Dynamo? (black background, bold text)
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/8107026/61866355-049e-4a7a-8fa4-818e6fb50079)

Maybe separate thought: I found the white background textbox that says "Select folder..." more eye-catching than the blue borderless icon next to it. So, I tried to click on the text but of course nothing happened. This is how Dynamo is too, but I find it frustrating that the box is not clickable. Black background would help, I think, as it makes it look less like a button, but it still looks like a field. Could clicking the field do the same as clicking the button (i.e. open the folder dialog box)? @Jingyi-Wen - thoughts?

**Comment by johnpierson** [comment]
Good point! We can definitely girly change the icon and make the text
clickable.
