### ISSUE TITLE
Package download improvements

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#2]
Hi!  I downloaded the package and upzipped it but then it was blocked and also a folder within a folder.  What do you think of making it a .7z to force people to use 7 zip which won't block it and also making it not unzip to  a folder within a folder?

**Comment by lillismith** [comment]
Nothing happens on starting graph migration assistant unless I have a file open.

1. From Dynamo home start Graph Migration Assistant
2. nothing happens
3. Start a new file
4. Migration assistant shows up

If we require starting a workspace, we should tell people this.  
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/60374ef1-c6d2-48a6-99e5-0668be87cbe2)

**Comment by arincakkin** [comment]
After we unzipped it,Which directory should paste to?

**Comment by lillismith** [comment]
Put it where your packages are e.g. C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Core\2.18\packages.  Make sure you unzipped it with 7zip or unblocked it first.

**Comment by arincakkin** [comment]
migration link doesnt appear under extensions:(

**Comment by lillismith** [comment]
Check that your package paths are pointing to the location where you put it and that it didn't get blocked by downloading it from the internet.

**Comment by arincakkin** [comment]
i did like this

![dynamocore](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/139764969/1b16df65-4295-4616-81ad-56164b5c7f11)

**Comment by lillismith** [comment]
There should be a folder in there called DynamoGraphMigrationAssistant t hat looks like this inside 
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/54daae1d-5a2e-4c8e-8950-5a1a84fcbceb)

**Comment by lillismith** [comment]
Are you sure you're downloading it from here? https://github.com/DynamoDS/DynamoGraphMigrationAssistant/releases/tag/0.0.11

**Comment by arincakkin** [comment]
yes correct. first one [DynamoGraphMigrationAssistant.7z]

**Comment by johnpierson** [comment]
> i did like this
> 
> ![dynamocore](https://user-images.githubusercontent.com/139764969/253972185-1b16df65-4295-4616-81ad-56164b5c7f11.png)

In your screenshot, why are you highlighting "Dynamo Core Runtime". That is not the correct folder by any means. You should unzip the folder and put that in packages.
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/15744724/2271c9ac-66e6-4c16-98c2-6cc54aa8757a)

The .7z folder turns into the `DynamoGraphMigrationAssistant` Folder, which then gets placed in the packages folder.

**Comment by arincakkin** [comment]
I think correct folder but still cant seen under the extensions
![dynamocore](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/139764969/08cb9da9-3007-4799-ac89-8d854e48ca22)

**Comment by lillismith** [comment]
Make sure you don't have a nested folder in there. Should look inside like my screenshot above (bin, dyf, extras, etc...)

**Comment by arincakkin** [comment]
Yes same like yours:(

**Comment by johnpierson** [comment]
@arincakkin - here is a video showing the **exact** process of unzipping and installing it. 
https://www.youtube.com/watch?v=LWnrnjOqV7A

Also worth noting, this tool does not "fix" any Dynamo graphs that simply do not work. If that is what you are expecting, I apologize, but the forums are better suited for your issue. https://forum.dynamobim.com/
