### ISSUE TITLE
Nothing happens on starting graph migration assistant unless I have a workspace open.

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#4]
Nothing happens on starting graph migration assistant unless I have a file open.

1. From Dynamo home start Graph Migration Assistant
2. nothing happens
3. Start a new file
4. Migration assistant shows up

If we require starting a workspace, we should tell people this.  
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/60374ef1-c6d2-48a6-99e5-0668be87cbe2)

_Originally posted by @lillismith in https://github.com/DynamoDS/DynamoGraphMigrationAssistant/issues/2#issuecomment-1555167939_

**Comment by johnpierson** [comment]
FWIW, this happens on Dynamo Team created extensions as well:
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/15744724/f6672a76-d206-4c42-b4bd-4b9780428bf7)

Graph node manager is clickable, but does nothing when clicking on it from the starting view.

Would be keen to know how to fix this @QilongTang
