### ISSUE TITLE
Trust warning during migration causes confusion

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#6]
The trust warning comes up during migration (for each sub folder too?)  What is actually happening here?  Is it running the graph or not because the run is blocked?  Is it doing the work?  Appears to move on, but then I'm not sure....   I think we need a utility to be able to trust the files' location(s) either in the actual migration assistant or just once when it starts running. 

![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/8d00669c-9f05-4916-8f46-c23d0c6380e2)

**Comment by QilongTang** [comment]
Looks like the migration output path needs to be trusted automatically. Our team should be able to help for sure.

**Comment by johnpierson** [comment]
This is fixed with the latest two releases. Might need to work on the language and warnings around the checkbox though.
