### ISSUE TITLE
Outdated Python engine warning is confusing during Graph Migration

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#7]
Outdated python engine warning comes up during  graph migration, but what is it doing?  Is it ruining my migration?  Can we just hit the "don't show Python engine warning" button on the Migration assistant? (default ON) 
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/78a1eb92-e248-43a8-82e0-39110920e0cf)

**Comment by QilongTang** [comment]
Looks like wrong screenshot on this issue?

**Comment by QilongTang** [comment]
Related task tracked as https://jira.autodesk.com/browse/DYN-5915
