### ISSUE TITLE
Parts of graph migration assistant UI are non-functional

### ISSUE THREAD

**Issue by lillismith** [DynamoDS/DynamoGraphUpdater#8]
Are these scroll bars?  The don't appear to work.  What is the white square? 
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/2932690/10a4ce6f-bde5-48d3-a916-0d3486682fb7)

**Comment by johnpierson** [comment]
The scroll bars should work and the white square is something weird from the controls (being inherited) let me see about styling those appropriately.

**Comment by johnpierson** [comment]
This is fixed now and the scrollbar is consistent with other Dynamo menus. If the style is not what is desired, this would be a Dynamo core change.
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/15744724/55125dd6-c92d-4f18-93db-c21dfa87f592)
